custombucket = "demo-capstoneproj-bucket"
table = "aws_capstoneproj_db_table"
databasehost = "demo-capstoneproj-db.ct3xpqmpfbl0.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "Admin!1234"
s3database = "aws_do_pgp_db"
kapp = "http://50.0.2.207:31010/"
